"""
CLI command to convert a Markdown file (generated by project2md) back to project structure for Ambulon.
Utilizes core logic from app.processing.core.md_to_project_converter.
Handles CLI arguments, configuration loading, and logging.
"""

import sys
import argparse
import logging
from pathlib import Path
from typing import Optional

from app.core.config_loader import load_config as load_app_config
from app.core.logging_config import setup_logging
from ..core.md_to_project_converter import md2project_logic

logger = logging.getLogger(__name__)

DEFAULT_CONFIG = {
    'processing': {
        'md2project': {
            'overwrite': False,
            'merge': False,
        }
    }
}

def main(argv=None):
    """
    Entry point with argv parameter for testability.

    Converts a Markdown file (typically generated by 'project2md') back into its
    original project directory structure. This involves extracting code blocks
    and file paths from Markdown headers, creating directories, and writing files.

    Configuration Hierarchy (from highest to lowest priority):
    1. Command-line arguments
    2. YAML configuration file (--config, e.g., config/processing.yaml)
    3. Environment variables
    4. Default values
    """
    parser = argparse.ArgumentParser(
        description="Converts a Markdown file back into its original project directory structure.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Configuration Hierarchy (from highest to lowest priority):
  1. Command-line arguments
  2. YAML configuration file (--config, e.g., config/processing.yaml)
  3. Environment variables
  4. Default values

Examples:
  # Basic conversion (auto-detect project name)
  ambulon md2project my_project.md

  # With custom output directory
  ambulon md2project my_project.md --output ./restored-project

  # Dry run to see what would be created
  ambulon md2project my_project.md --dry-run

  # Merge with existing directory
  ambulon md2project my_project.md --merge

  # Overwrite existing files
  ambulon md2project my_project.md --overwrite
        """
    )

    # Positional arguments
    parser.add_argument(
        "markdown_file",
        type=Path,
        help="Path to Markdown file generated by 'project2md'."
    )

    # Options
    parser.add_argument(
        "-o", "--output",
        type=Path,
        help="Output directory for the recreated project (default: uses project name from Markdown)."
    )

    # Configuration
    parser.add_argument(
        "-c", "--config",
        type=Path,
        dest="config_path",
        help="Path to a YAML configuration file (e.g., config/processing.yaml)."
    )

    # Global options
    parser.add_argument(
        "-v", "--verbose",
        action="store_true",
        help="Enable verbose logging."
    )
    parser.add_argument(
        "-q", "--quiet",
        action="store_true",
        help="Suppress most output messages."
    )

    # Conversion specific options
    parser.add_argument(
        "-n", "--dry-run",
        action="store_true",
        help="Simulate what would be done without creating or modifying any files."
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Overwrite existing files and directories."
    )
    parser.add_argument(
        "--no-overwrite",
        action="store_true",
        help="Do not overwrite existing files (will prompt if file exists)."
    )
    parser.add_argument(
        "--merge",
        action="store_true",
        help="Merge with existing directory, preserving files not in Markdown. Overrides --overwrite if both are set."
    )

    args = parser.parse_args(argv)

    # Validate markdown file exists
    if not args.markdown_file.exists():
        print(f"Error: Markdown file does not exist: {args.markdown_file}", file=sys.stderr)
        return 1
    if not args.markdown_file.is_file():
        print(f"Error: Path is not a file: {args.markdown_file}", file=sys.stderr)
        return 1

    # Setup logging
    log_level = logging.DEBUG if args.verbose else (logging.WARNING if args.quiet else logging.INFO)
    setup_logging(level=log_level, log_file_prefix="md2project")
    logger.info("[START] Starting md2project module.")
    logger.debug(f"CLI arguments: {vars(args)}")

    # Load configuration
    config = load_app_config(str(args.config_path) if args.config_path else None, DEFAULT_CONFIG)
    md2project_config = config['processing']['md2project']

    # Apply CLI overrides (highest priority) and resolve config
    if args.overwrite:
        final_overwrite = True
    elif args.no_overwrite:
        final_overwrite = False
    else:
        final_overwrite = md2project_config.get('overwrite', DEFAULT_CONFIG['processing']['md2project']['overwrite'])

    final_merge = args.merge if args.merge else md2project_config.get('merge', DEFAULT_CONFIG['processing']['md2project']['merge'])

    # --merge takes precedence over --overwrite
    if final_merge:
        final_overwrite = False

    # Execute core logic
    try:
        exit_code, generated_path = md2project_logic(
            markdown_file=args.markdown_file,
            output_dir=args.output,
            dry_run=args.dry_run,
            overwrite=final_overwrite,
            merge=final_merge
        )

        if exit_code == 0:
            if generated_path:
                try:
                    relative_path = generated_path.relative_to(Path.cwd())
                except ValueError:
                    relative_path = generated_path.resolve()
                print(f"\n✓ Project recreation successful!\nOutput directory: {relative_path}")
            else:
                print("\n✓ Project recreation successful (dry run, or no files to generate).")
            return 0
        else:
            logger.error("Failed to recreate project from Markdown file.")
            return 1
    except Exception as e:
        logger.error(f"Error during project recreation: {e}", exc_info=True)
        return 1

if __name__ == '__main__':
    sys.exit(main())
