"""
CLI command to convert a Markdown file (generated by project2md) back to project structure for Ambulon.
Utilizes core logic from app.processing.core.md_to_project_converter.
Handles CLI arguments, configuration loading, and logging.
"""

import typer
import logging
import os
from pathlib import Path
from typing import Optional, Set

from app.core.config_loader import load_config as load_app_config
from app.core.logging_config import setup_logging
from ..core.md_to_project_converter import md2project_logic

logger = logging.getLogger(__name__)

app = typer.Typer()

DEFAULT_CONFIG = {
    'processing': {
        'md2project': {
            'overwrite': False,
            'merge': False,
        }
    }
}

@app.command(
    help="""
    Converts a Markdown file (typically generated by 'project2md') back into its
    original project directory structure. This involves extracting code blocks
    and file paths from Markdown headers, creating directories, and writing files.

    Configuration Hierarchy (from highest to lowest priority):
    1. Command-line arguments
    2. YAML configuration file (`--config`, e.g., `config/processing.yaml`)
    3. Environment variables
    4. Default values
    """
)
def main(
    markdown_file: Path = typer.Argument(..., help="Path to Markdown file generated by 'project2md'.", exists=True, file_okay=True, dir_okay=False, readable=True),
    output: Optional[Path] = typer.Option(None, "--output", "-o", help="Output directory for the recreated project (default: uses project name from Markdown)."),
    config_path: Optional[Path] = typer.Option(None, "--config", "-c", help="Path to a YAML configuration file (e.g., config/processing.yaml)."),
    
    # Global options
    verbose: bool = typer.Option(False, "--verbose", "-v", help="Enable verbose logging."),
    quiet: bool = typer.Option(False, "--quiet", "-q", help="Suppress most output messages."),

    # Conversion specific options
    dry_run: bool = typer.Option(False, "--dry-run", "-n", help="Simulate what would be done without creating or modifying any files."),
    overwrite: Optional[bool] = typer.Option(None, "--overwrite", help="Overwrite existing files and directories. Set with --no-overwrite to force prompt."),
    no_overwrite: bool = typer.Option(False, "--no-overwrite", help="Do not overwrite existing files (will prompt if file exists)."),
    merge: Optional[bool] = typer.Option(None, "--merge", help="Merge with existing directory, preserving files not in Markdown. Overrides --overwrite if both are set."),
):
    """
    CLI for converting Markdown files back to project structure.
    """
    # Configure logging
    log_level = logging.DEBUG if verbose else (logging.WARNING if quiet else logging.INFO)
    setup_logging(level=log_level, log_file_prefix="md2project")
    logger.info("[START] Starting md2project module.")
    logger.debug(f"CLI arguments: {typer.Context.get_current().params}")

    # Load configuration
    config = load_app_config(str(config_path) if config_path else None, DEFAULT_CONFIG)
    md2project_config = config['processing']['md2project']

    # Apply CLI overrides (highest priority) and resolve config
    final_overwrite = overwrite if overwrite is not None else md2project_config.get('overwrite', DEFAULT_CONFIG['processing']['md2project']['overwrite'])
    if no_overwrite:
        final_overwrite = False
    
    final_merge = merge if merge is not None else md2project_config.get('merge', DEFAULT_CONFIG['processing']['md2project']['merge'])
    if final_merge: # --merge takes precedence over --overwrite
        final_overwrite = False

    # Execute core logic
    exit_code, generated_path = md2project_logic(
        markdown_file=markdown_file,
        output_dir=output,
        dry_run=dry_run,
        overwrite=final_overwrite,
        merge=final_merge
    )

    if exit_code == 0:
        if generated_path:
            try:
                relative_path = generated_path.relative_to(Path.cwd())
            except ValueError:
                relative_path = generated_path.resolve()
            print(f"\n✓ Project recreation successful!\nOutput directory: {relative_path}")
        else:
            print("\n✓ Project recreation successful (dry run, or no files to generate).")
        raise typer.Exit(code=0)
    else:
        logger.error("Failed to recreate project from Markdown file.")
        raise typer.Exit(code=1)

if __name__ == '__main__':
    app()