"""
Utilitaires pour le traitement et le nettoyage des fichiers SVG.
"""

from __future__ import annotations

import re
from typing import Optional


def clean_svg_content(
    svg_content: str,
    make_responsive: bool = True,
    remove_declarations: bool = True
) -> str:
    """
    Nettoie le contenu SVG pour l'intégration inline.
    
    Args:
        svg_content: Contenu SVG brut
        make_responsive: Rend le SVG responsive (supprime width/height fixes)
        remove_declarations: Supprime déclarations XML et DOCTYPE
        
    Returns:
        Contenu SVG nettoyé
    """
    # Supprime déclaration XML
    if remove_declarations:
        svg_content = re.sub(r'<\?xml[^>]*\?>\s*', '', svg_content)
        svg_content = re.sub(r'<!DOCTYPE[^>]*>\s*', '', svg_content)
    
    # Supprime commentaires de génération
    svg_content = re.sub(r'<!--[^>]*Generated by [^>]*-->\s*', '', svg_content)
    svg_content = re.sub(r'<!--\s*Title:[^>]*-->\s*', '', svg_content)
    
    # Corrige preserveAspectRatio
    svg_content = re.sub(
        r'preserveAspectRatio="none"',
        'preserveAspectRatio="xMidYMid meet"',
        svg_content
    )
    
    if make_responsive:
        # Supprime attributs width/height
        svg_content = re.sub(r'<svg([^>]*)\swidth="[^"]*"', r'<svg\1', svg_content)
        svg_content = re.sub(r'<svg([^>]*)\sheight="[^"]*"', r'<svg\1', svg_content)
        
        # Supprime styles width/height inline
        svg_content = re.sub(r'style="([^"]*?)width:\s*\d+px;?([^"]*)"', r'style="\1\2"', svg_content)
        svg_content = re.sub(r'style="([^"]*?)height:\s*\d+px;?([^"]*)"', r'style="\1\2"', svg_content)
        
        # Nettoie attributs style vides
        svg_content = re.sub(r'style="\s*;?\s*"', '', svg_content)
    
    return svg_content.strip()


def optimize_svg_for_pdf(
    svg_content: str,
    page_orientation: Optional[str] = None
) -> str:
    """
    Optimise un SVG pour la génération PDF.
    
    Args:
        svg_content: Contenu SVG
        page_orientation: 'portrait', 'landscape' ou None
        
    Returns:
        SVG optimisé
    """
    # Nettoie d'abord
    svg_content = clean_svg_content(svg_content)
    
    # Détermine les dimensions selon l'orientation
    if page_orientation == 'portrait':
        max_width = "700px"
    elif page_orientation == 'landscape':
        max_width = "900px"
    else:
        max_width = None
    
    if max_width:
        # Ajoute un style pour limiter la largeur
        if 'style="' in svg_content:
            svg_content = re.sub(
                r'<svg([^>]*?)style="([^"]*)"',
                rf'<svg\1style="\2; max-width: {max_width}; height: auto;"',
                svg_content
            )
        else:
            svg_content = re.sub(
                r'<svg',
                rf'<svg style="max-width: {max_width}; height: auto;"',
                svg_content
            )
    
    return svg_content


def extract_svg_viewbox(svg_content: str) -> Optional[str]:
    """
    Extrait la valeur viewBox d'un SVG.
    
    Args:
        svg_content: Contenu SVG
        
    Returns:
        Valeur viewBox ou None
    """
    match = re.search(r'viewBox="([^"]+)"', svg_content)
    return match.group(1) if match else None


def get_svg_dimensions(svg_content: str) -> tuple[Optional[str], Optional[str]]:
    """
    Extrait les dimensions d'un SVG.
    
    Args:
        svg_content: Contenu SVG
        
    Returns:
        Tuple (width, height) ou (None, None)
    """
    width_match = re.search(r'width="([^"]+)"', svg_content)
    height_match = re.search(r'height="([^"]+)"', svg_content)
    
    width = width_match.group(1) if width_match else None
    height = height_match.group(1) if height_match else None
    
    return width, height


def wrap_svg_for_html(
    svg_content: str,
    diagram_type: str = "",
    add_container: bool = True
) -> str:
    """
    Enveloppe un SVG dans une structure HTML.
    
    Args:
        svg_content: Contenu SVG
        diagram_type: Type de diagramme (pour la classe CSS)
        add_container: Ajoute un div conteneur
        
    Returns:
        HTML avec le SVG
    """
    css_class = f"diagram diagram-{diagram_type}" if diagram_type else "diagram"
    
    if add_container:
        return f'<div class="{css_class}">\n{svg_content}\n</div>'
    else:
        return svg_content


def is_valid_svg(content: str) -> bool:
    """
    Vérifie si le contenu est un SVG valide.
    
    Args:
        content: Contenu à vérifier
        
    Returns:
        True si c'est un SVG valide
    """
    content = content.strip()
    
    # Doit commencer par <svg ou contenir <svg
    if not re.search(r'<svg[\s>]', content, re.IGNORECASE):
        return False
    
    # Doit avoir une balise fermante
    if not re.search(r'</svg>', content, re.IGNORECASE):
        return False
    
    return True
