"""
Core logic for adding a Table of Contents (TOC) to Markdown files in Ambulon.
Parses Markdown, extracts headings, generates hierarchical TOC with anchor links.
"""

import re
import sys
import logging
from pathlib import Path
from typing import List, Tuple, Dict, Any, Optional, Set

from .markdown_toc_checker import detect_toc_markers

logger = logging.getLogger(__name__)


def remove_existing_toc(md_content: str, keep_toc_marker: bool = True) -> str:
    """
    Remove existing TOC from markdown content.
    
    Detects and removes:
    - HTML TOC blocks (## Table des matières ... </ul>)
    - TOC anchor tags (<a id="toc-..."></a>)
    - Optionally [TOC] markers (controlled by keep_toc_marker)
    
    Args:
        md_content: Markdown content that may contain a TOC
        keep_toc_marker: If True, preserve [TOC] markers for replacement
        
    Returns:
        Content with TOC removed
    """
    content = md_content
    
    # Remove HTML TOC block (from ## Table des matières to closing </ul>)
    # Pattern matches the TOC block generated by generate_toc_markdown
    toc_pattern = r'^## Table des matières\s*\n\s*<ul>.*?</ul>\s*(?:\n---\s*)?'
    content = re.sub(toc_pattern, '', content, flags=re.MULTILINE | re.DOTALL)
    
    # Remove TOC line anchors (<a id="toc-..."></a>)
    content = re.sub(r'<a id="toc-[^"]+"></a>', '', content)
    
    # Remove [TOC] marker only if keep_toc_marker is False
    if not keep_toc_marker:
        content = re.sub(r'^\[TOC\]\s*$', '', content, flags=re.MULTILINE)
    
    # Clean up excessive empty lines left behind
    content = re.sub(r'\n{3,}', '\n\n', content)
    
    return content


def is_toc_heading(text: str) -> bool:
    """Check if a heading is the TOC title itself (should be excluded)."""
    toc_patterns = [
        r'table\s+(?:des\s+)?mati[èe]res',  # Table des matières
        r'table\s+of\s+contents',           # Table of Contents
        r'sommaire',                         # Sommaire
    ]
    text_lower = text.lower()
    for pattern in toc_patterns:
        if re.search(pattern, text_lower):
            return True
    return False


def extract_headings(md_content: str) -> List[Dict[str, Any]]:
    """
    Extract headings from Markdown content.

    Args:
        md_content: Markdown content as string

    Returns:
        List of heading dictionaries with level, text, and line number
    """
    headings = []
    lines = md_content.split('\n')

    # Pattern to match markdown headings: # Heading, ## Heading, etc.
    # Optionally captures custom IDs in {#id} format
    heading_pattern = re.compile(r'^(#{1,6})\s+(.+?)(?:\s*\{#([a-zA-Z0-9\-_]+)\})?$')

    for line_num, line in enumerate(lines):
        match = heading_pattern.match(line)
        if match:
            level = len(match.group(1))  # Count number of #
            text = match.group(2).strip()
            
            # Skip TOC headings (don't include TOC title in the TOC)
            if is_toc_heading(text):
                continue
            
            custom_id = match.group(3) if match.lastindex >= 3 else None  # Custom ID if specified

            headings.append({
                'level': level,
                'text': text,
                'line': line_num,
                'custom_id': custom_id,
                'id': None  # Will be generated later
            })

    return headings


def generate_id(text: str, existing_ids: Set[str]) -> str:
    """
    Generate a unique ID from heading text.

    Args:
        text: Heading text
        existing_ids: Set of already used IDs

    Returns:
        Unique ID string
    """
    # Convert to lowercase, replace spaces with hyphens, remove special chars
    base_id = re.sub(r'[^\w\s-]', '', text.lower())
    base_id = re.sub(r'[-\s]+', '-', base_id).strip('-')

    # Ensure uniqueness
    unique_id = base_id
    counter = 1
    while unique_id in existing_ids:
        unique_id = f"{base_id}-{counter}"
        counter += 1

    existing_ids.add(unique_id)
    return unique_id


def generate_toc_markdown(headings: List[Dict[str, Any]], min_level: int = 1, max_level: int = 6) -> str:
    """
    Generate HTML table of contents with anchor IDs for each line.

    Each TOC line gets an ID like 'toc-{heading-id}' so back-to-TOC links
    can point to the specific line, not just the TOC in general.

    Note: We generate HTML directly instead of Markdown because HTML anchor tags
    at the start of Markdown list items prevent proper list parsing.

    Args:
        headings: List of heading dictionaries
        min_level: Minimum heading level to include (default: 1)
        max_level: Maximum heading level to include (default: 6)

    Returns:
        HTML string for TOC with anchor IDs
    """
    if not headings:
        return ""

    toc_lines = ['## Table des matières', '', '<ul>']

    # Filter headings by level
    filtered_headings = [h for h in headings if min_level <= h['level'] <= max_level]

    if not filtered_headings:
        return ""

    # Find the minimum level to use as base for indentation
    base_level = min(h['level'] for h in filtered_headings)

    # Track current nesting level to manage nested <ul> tags
    current_level = base_level
    level_stack = []

    for heading in filtered_headings:
        level = heading['level']
        text = heading['text']
        heading_id = heading['id']
        toc_line_id = f"toc-{heading_id}"

        # Close nested lists if we're going back to a higher level
        while current_level > level:
            toc_lines.append('</ul>')
            toc_lines.append('</li>')
            current_level -= 1

        # Open nested list if we're going deeper
        if level > current_level:
            toc_lines.append('<ul>')
            current_level = level

        # Close previous list item if at same level (except for first item)
        if level_stack and level_stack[-1] == level:
            toc_lines.append('</li>')

        # Add list item with anchor and link
        toc_lines.append(f'<li><a id="{toc_line_id}"></a><a href="#{heading_id}">{text}</a>')

        level_stack.append(level)

    # Close all remaining list items and lists
    toc_lines.append('</li>')
    while current_level > base_level:
        toc_lines.append('</ul>')
        toc_lines.append('</li>')
        current_level -= 1

    toc_lines.append('</ul>')
    toc_lines.append('')
    toc_lines.append('---')
    toc_lines.append('')

    return '\n'.join(toc_lines)


def add_anchors_to_headings(md_content: str, headings: List[Dict[str, Any]]) -> str:
    """
    Add HTML anchor IDs to Markdown headings.

    Since Markdown doesn't have native ID support, we add HTML anchors
    before each heading for navigation.

    Args:
        md_content: Original Markdown content
        headings: List of headings with generated IDs

    Returns:
        Modified Markdown content with anchors
    """
    lines = md_content.split('\n')
    
    # Build a set of heading IDs that need anchors (those without custom_id)
    heading_ids_to_add = {
        h['id']: h for h in headings 
        if not h.get('custom_id')
    }
    
    if not heading_ids_to_add:
        return md_content
    
    # Pattern to match markdown headings
    heading_pattern = re.compile(r'^(#{1,6})\s+(.+?)(?:\s*\{#([a-zA-Z0-9\-_]+)\})?$')
    
    # Find headings in content and add anchors
    # Process in reverse order to avoid line number shifts
    replacements = []
    
    for line_num, line in enumerate(lines):
        match = heading_pattern.match(line)
        if match:
            level = len(match.group(1))
            text = match.group(2).strip()
            custom_id = match.group(3) if match.lastindex >= 3 else None
            
            # Skip if has custom ID
            if custom_id:
                continue
            
            # Generate ID for this heading
            heading_id = re.sub(r'[^\w\s-]', '', text.lower())
            heading_id = re.sub(r'[\s_]+', '-', heading_id).strip('-')
            
            # Check if this heading needs an anchor
            if heading_id in heading_ids_to_add:
                anchor = f'<a id="{heading_id}"></a>'
                replacements.append((line_num, anchor))
    
    # Apply replacements in reverse order
    for line_num, anchor in sorted(replacements, key=lambda x: x[0], reverse=True):
        lines.insert(line_num, anchor)

    return '\n'.join(lines)


def add_toc_to_markdown_logic(
    input_file: Path,
    output_file: Path,
    min_level: int = 1,
    max_level: int = 6,
    force: bool = False,
) -> Tuple[int, Optional[Path]]:
    """
    Core logic to add a table of contents to a Markdown file.

    Args:
        input_file: Path to input Markdown file
        output_file: Path to output file
        min_level: Minimum heading level to include in TOC (1-6)
        max_level: Maximum heading level to include in TOC (1-6)
        force: If True, replace existing TOC; if False, skip if TOC exists

    Returns:
        A tuple: (exit_code: int, generated_path: Optional[Path])
    """
    if not input_file.exists():
        logger.error(f"Error: Input file '{input_file}' does not exist.")
        return 1, None

    if not input_file.is_file():
        logger.error(f"Error: '{input_file}' is not a file.")
        return 1, None

    logger.info(f"Processing: {input_file}")
    logger.info(f"Output: {output_file}")

    try:
        # Read Markdown content
        with open(input_file, 'r', encoding='utf-8') as f:
            md_content = f.read()

        # Check if TOC already exists
        toc_check = detect_toc_markers(md_content)
        
        # [TOC] marker should be replaced, not considered as "existing TOC"
        # Only skip if actual HTML TOC or Markdown TOC section exists
        has_real_toc = toc_check['html_nav'] or toc_check['markdown_toc_section']
        has_toc_marker = toc_check['toc_marker']
        
        if has_real_toc and not force:
            logger.info("TOC already exists in file (use --force to replace)")
            if toc_check['html_nav']:
                logger.info("  - HTML <nav> TOC detected")
            if toc_check['markdown_toc_section']:
                logger.info("  - Markdown TOC section detected")
            # Copy file as-is
            output_file.parent.mkdir(parents=True, exist_ok=True)
            with open(output_file, 'w', encoding='utf-8') as f:
                f.write(md_content)
            logger.info(f"File copied without changes: {output_file}")
            return 0, output_file
        elif has_toc_marker and not has_real_toc:
            logger.info("[TOC] marker found - will replace with generated TOC")

        # Remove existing TOC (keep [TOC] marker for replacement)
        md_content = remove_existing_toc(md_content, keep_toc_marker=True)

        # Extract headings
        headings = extract_headings(md_content)

        logger.info(f"Found {len(headings)} headings.")

        if not headings:
            logger.warning("No headings found in Markdown file. No TOC will be added.")
            # Still write the file
            output_file.parent.mkdir(parents=True, exist_ok=True)
            with open(output_file, 'w', encoding='utf-8') as f:
                f.write(md_content)
            logger.info(f"File copied without TOC: {output_file}")
            return 0, output_file

        # Generate IDs for headings
        existing_ids: Set[str] = set()
        for heading in headings:
            if heading.get('custom_id'):
                heading['id'] = heading['custom_id']
                existing_ids.add(heading['id']) # Add custom IDs to ensure uniqueness check works
            else:
                heading['id'] = generate_id(heading['text'], existing_ids)

            logger.debug(f"  {'#' * heading['level']} {heading['text']} (#{heading['id']})")

        # Generate TOC Markdown
        toc_md = generate_toc_markdown(headings, min_level, max_level)

        # Find insertion point for TOC:
        # 1. If [TOC] marker exists, replace it
        # 2. Otherwise, insert after the first H1 (to keep title/version/date before TOC)
        toc_marker_match = re.search(r'^\[TOC\]\s*$', md_content, re.MULTILINE)
        
        if toc_marker_match:
            # Replace [TOC] marker with actual TOC
            before_marker = md_content[:toc_marker_match.start()]
            after_marker = md_content[toc_marker_match.end():]
            md_content_with_toc = before_marker + toc_md + '\n' + after_marker
        else:
            # Find first H1 to insert TOC after it
            first_h1_idx = None
            for h in headings:
                if h['level'] == 1:
                    first_h1_idx = h['line']
                    break
            
            if first_h1_idx is not None:
                # Find the end of the first H1 line (including any following metadata lines)
                lines = md_content.split('\n')
                insert_line = first_h1_idx + 1
                
                # Skip empty lines and metadata lines (Version:, Date:, Auteur:, etc.) after H1
                while insert_line < len(lines) and (
                    not lines[insert_line].strip() or
                    lines[insert_line].strip().startswith(('Version', 'Date', 'Auteur', 'Author', 'Mise à jour'))
                ):
                    if lines[insert_line].strip():
                        insert_line += 1
                    else:
                        # Keep one empty line as separator, then continue if more metadata
                        insert_line += 1
                        break
                
                # Insert TOC at the calculated position
                before_toc = '\n'.join(lines[:insert_line])
                after_toc = '\n'.join(lines[insert_line:])
                md_content_with_toc = before_toc + '\n\n' + toc_md + '\n' + after_toc
            else:
                # No H1 found, prepend at beginning
                md_content_with_toc = toc_md + '\n' + md_content

        # Add anchors to headings in the content (after TOC is positioned)
        final_content = add_anchors_to_headings(md_content_with_toc, headings)

        # Ensure output directory exists
        output_file.parent.mkdir(parents=True, exist_ok=True)

        # Write output
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(final_content)

        filtered_count = len([h for h in headings if min_level <= h['level'] <= max_level])

        logger.info(f"Markdown with TOC created: {output_file}")
        logger.info(f"Total headings found:     {len(headings)}")
        logger.info(f"Headings in TOC:          {filtered_count}")
        logger.info(f"Heading level range:      {min_level} - {max_level}")
        
        file_size = output_file.stat().st_size
        if file_size > 1024 * 1024:
            size_str = f"{file_size / (1024 * 1024):.2f} MB"
        elif file_size > 1024:
            size_str = f"{file_size / 1024:.2f} KB"
        else:
            size_str = f"{file_size} bytes"
        logger.info(f"Output file size:         {size_str}")

        return 0, output_file

    except Exception as e:
        logger.error(f"Error: Failed to add TOC: {e}", exc_info=True)
        return 1, None
