"""
Core logic for converting a Markdown file (generated by project2md) back to project structure.
Parses Markdown file and recreates the original project structure.
"""

import sys
import logging
from pathlib import Path
from typing import Optional, Set, Tuple

logger = logging.getLogger(__name__)

# Import du parser local (copié depuis dyag)
from .md2project_parser import Md2ProjectParser


def md2project_logic(
    markdown_file: Path,
    output_dir: Optional[Path] = None,
    dry_run: bool = False,
    overwrite: bool = False,
    merge: bool = False,
) -> Tuple[int, Optional[Path]]:
    """
    Core logic to convert Markdown file (from project2md) back to project structure.

    Args:
        markdown_file: Path to Markdown file generated by project2md
        output_dir: Output directory for project (default: {project_name}/)
        dry_run: Show what would be done without creating files
        overwrite: Overwrite existing files
        merge: Merge with existing files (don't delete existing)

    Returns:
        A tuple: (exit_code: int, generated_path: Optional[Path])
    """

    if not markdown_file.exists():
        logger.error(f"Error: Markdown file '{markdown_file}' does not exist.")
        return 1, None

    if not markdown_file.is_file():
        logger.error(f"Error: '{markdown_file}' is not a file.")
        return 1, None

    logger.info(f"Parsing Markdown: {markdown_file}")

    try:
        # Parse Markdown
        parser = Md2ProjectParser(verbose=logger.isEnabledFor(logging.DEBUG)) # Pass verbose state from logger
        project = parser.parse_file(str(markdown_file))

        logger.info(f"Project name: {project.name}")
        logger.info(f"Files found: {len(project.files)}")

        # Validate structure
        issues = parser.validate_structure(project)
        if issues:
            logger.warning("[WARNING] Issues detected:")
            for issue in issues:
                logger.warning(f"  - {issue}")

        if not project.files:
            logger.error("[ERROR] No files extracted from Markdown.")
            return 1, None

        # Determine output directory
        if output_dir is None:
            output_path = Path(project.name)
        else:
            output_path = output_dir

        output_path = output_path.resolve()

        logger.info(f"Output directory: {output_path}")

        # Check if output directory exists
        if output_path.exists() and not merge:
            if not overwrite:
                logger.error(
                    f"Output directory '{output_path}' already exists. "
                    f"Use --overwrite or --merge to continue."
                )
                return 1, None
            else:
                logger.warning(f"Overwriting existing directory: {output_path}")

        # Dry run mode
        if dry_run:
            logger.info("[DRY RUN] Would create the following structure:\n")
            logger.info(f"{output_path}/")
            for file_entry in project.files:
                file_path_in_output = output_path / file_entry.path
                size = len(file_entry.content.encode('utf-8'))
                logger.info(f"  {file_entry.path} ({size} bytes, {file_entry.language or 'text'})")
            logger.info(f"\n[DRY RUN] Total: {len(project.files)} files.")
            return 0, output_path

        # Create project structure
        logger.info("\nCreating project structure...")

        created_files = []
        skipped_files = []
        errors = []

        for file_entry in project.files:
            file_path_in_output = output_path / file_entry.path

            try:
                # Check if file exists and not overwriting
                if file_path_in_output.exists() and not overwrite and not merge:
                    skipped_files.append(file_entry.path)
                    logger.info(f"Skipped: {file_entry.path} (already exists)")
                    continue

                # Create parent directories
                file_path_in_output.parent.mkdir(parents=True, exist_ok=True)

                # Write file
                file_path_in_output.write_text(file_entry.content, encoding='utf-8')
                created_files.append(file_entry.path)

                size = len(file_entry.content.encode('utf-8'))
                logger.info(f"Created: {file_entry.path} ({size} bytes)")

            except Exception as e:
                errors.append((file_entry.path, str(e)))
                logger.error(f"Failed to create {file_entry.path}: {e}")

        # Summary
        logger.info("="*70)
        logger.info(f"Project created: {output_path}")
        logger.info("="*70)
        logger.info(f"Created: {len(created_files)} files.")

        if skipped_files:
            logger.info(f"Skipped: {len(skipped_files)} files (already exist).")

        if errors:
            logger.error(f"Errors: {len(errors)} files failed.")
            for path, error in errors[:5]:  # Show first 5 errors
                logger.error(f"  - {path}: {error}")
            if len(errors) > 5:
                logger.error(f"  ... and {len(errors) - 5} more errors.")
            return 1, None
        
        logger.info("="*70)

        return 0, output_path

    except Exception as e:
        logger.error(f"Error: Failed to convert Markdown to project: {e}", exc_info=True)
        return 1, None
